name: Push Contentful models to main

on:
  push:
    branches:
      - "main"

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ENVIRONMENT: master
  MODELBERRY_PROJECT_NAME: contentful-gitflow-test
  CONTENTFUL_PERSONAL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PERSONAL_ACCESS_TOKEN }}

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install packages
        run: |
          npm config set registry https://registry.npmjs.org
          npm install

      - name: Push models to Contentful
        run: |
          npx mbfactory push models --yes ./contentful/types/index.ts
